models/contact.py
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True) 
    fullname = db.Column(db.String(100)) 
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URI
app = Flask(__name__)


app.secret_key= "secret key"
app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint
from  flask import render_template, request, redirect, url_for, flash
from models.contact import  Contact
from utils.db import db


contacts = Blueprint('contacts', __name__)

@contacts.route('/')
def index():
    contacts = Contact.query.all()
    return render_template("index.html", contacts=contacts)


@contacts.route('/new', methods=['POST']) 
def add_contact():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']

    new_contact = Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()
    
    flash("Contact added successfully!")

    return redirect(url_for('contacts.index'))

@contacts.route('/update/<id>', methods = ['POST','GET'])
def update_contact(id):
    contact = Contact.query.get(id)

    if request.method == 'POST':
        contact.fullname = request.form["fullname"]
        contact.email = request.form["email"]
        contact.phone = request.form["phone"]

        db.session.commit()

        flash("Contact updated successfully!")
        
        return redirect(url_for("contacts.index"))

    return render_template("update.html", contact=contact)

@contacts.route('/delete/<id>')
def delete_contact(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)              #delete es diferente del nombre de la funcion
    db.session.commit()

    flash("Contact deleted successfully!")

    return redirect(url_for('contacts.index'))

@contacts.route('/about')
def about():
    return render_template("about.html")

templates/index.html
{% extends 'layout.html' %}
{% block body %}


<div class="row">
    <div class="col-md-5">
        {% include 'partials/_messages.html' %}

        {% include 'partials/_contactForm.html' %}
    </div>
    
    <div class="col-md-7">
        {% for contact in contacts%}        

        <div class="card mb-1 text-white bg-dark">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h5>{{contact.fullname}}</h5>
                    <div>
                        <a href="{{ url_for('contacts.update_contact', id=contact.id) }}" class="btn bg-black text-white btn-sm rounded-0">Update</a>
                        <a href="{{ url_for('contacts.delete_contact', id=contact.id) }}" class="btn btn-danger btn-sm rounded-0">Delete</a> 
                    </div>
                </div>
                <p>{{contact.email}}</p>
                <p>{{contact.phone}}</p>

            </div>
        </div>      
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask-Alchemy-CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
</head>
<body>

    {% include('partials/_navbar.html') %}

    <div class="container p-2">
        
        {% block body %}
        {% endblock %}
    
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/partials/_contactForm.html
<form action="/new" method="POST" class="card bg-dark text-light">

    <div class="card-body p-4">
        <div class="mb-3">
            <label for="fullname">Write your fullname:</label>
            <input type="text" name="fullname" placeholder="Write your fullname" class="form-control rounded-0 bg-dark border-0 text-white">
        </div>
        
        <div class="mb-3">
            <label for="email">Write your email:</label>
            <input type="text" name="email" placeholder="Write your email" class="form-control rounded-0 bg-dark border-0 text-white">
        </div>

        <div class="mb-3">
            <label for="phone">Write your phone:</label>
            <input type="text" name="phone" placeholder="Write your phone" class="form-control rounded-0 bg-dark border-0 text-white">
        </div>
        <button class="btn btn-primary">save</button>
    </div>

</form>

templates/partials/_messages.html
{% with messages = get_flashed_messages() %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif%}

{% endwith%}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">Flask SQLAlchemy CRUD</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/update.html
{% extends 'layout.html' %}
{% block body %}

<div class="row">
    <div class="col-md-4 offset-md-4">
        <form action="/update/{{contact.id}}" method="POST" class="card bg-dark text-white">

            <div class="card-body p-4">
                <div class="mb-3">
                    <label for="fullname">Write your fullname</label>
                    <input type="text" name="fullname" placeholder="Write your fullname" value="{{contact.fullname}}" class="form-control rounded-0 bg-dark border-0 text-white"
                    />
                </div>
            
                <div class="mb-3">
                    <label for="email">Write your email</label>
                    <input type="text" name="email" placeholder="Write your email" value="{{contact.email}}" class="form-control rounded-0 bg-dark border-0 text-white"
                    />
                </div>
                
                <div class="mb-3">
                    <label for="phone">Write your phone</label>       
                    <input type="text" name="phone" placeholder="Write your phone" value="{{contact.phone}}" class="form-control rounded-0 bg-dark border-0 text-white"
                    />
                </div>

                <button class="btn btn-secondary">Update</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}